version: '3.7'
services:
    sqlserver1:
        build: 
          context: ./
          dockerfile: dockerfile
        ports:
          - "15789:1433"
        env_file:
          - sqlserver.env
          - sapassword.env
        volumes:
          - type: volume
            source: data
            target: /var/opt/mssql
volumes:
  data:
