version: "3.2"
services:
  mssql:
    hostname: mssqletl
    privileged: true
    restart: always
    build:
      context: mssql/
      dockerfile: dockerfile
    ports:
      - 1433:1433
    environment:
          SA_PASSWORD: "1A horse cannot unlock sheeps!"
          ACCEPT_EULA: "Y"
          HOSTNAME: mssqletl
          MSSQL_AGENT_ENABLED: True
          # USER: 1001  
    # env_file:
          # - sqlserver.env
          # - mssql/sapassword.env      
    volumes:
      - type: volume
        source: data
        target: /var/opt/mssql
      - /mnt/cloudbox:/mnt/cloudbox
      - /mnt/backup_drive:/mnt/backup_drive


    # cap_add:
    #   - SYS_ADMIN 
    #   - DAC_READ_SEARCH
    #   - CAP_DAC_READ_SEARCH
  backend:
    build: DbTask
    # volumes:
    #   - logs:/var/log/
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    depends_on:
      - "mssql"
    volumes:
      - /mnt/cloudbox:/mnt/cloudbox
    restart: always
  backup:
    build:
      context: DbBackup
      args:
        BACKUP_SERVICE_MODE: ${BACKUP_SERVICE_MODE}
    restart: always
    # depends_on:
      # - "mssql"
    volumes:
      - /mnt/cloudbox:/mnt/cloudbox
      - /mnt/backup_drive:/mnt/backup_drive
  bot:
    build:
      context: Bot
      args:
        BACKUP_SERVICE_MODE: ${BACKUP_SERVICE_MODE}
    # depends_on:
      # - "mssql"
    volumes:
      - /mnt/cloudbox:/mnt/cloudbox
    restart: always
volumes:
  data:

  # webdav:
  #   driver: fentas/davfs
  #   driver_opts:
  #     # type: cifs    
  #     remote: "//u312939.your-storagebox.de/backup"
  #     o: "username=u312939,password=Qr78R4YqxWZyF9Q7,vers=3.0,dir_mode=0777,file_mode=0777"
  # cifs_mount:
  #   driver: local
  #   driver_opts:
  #     type: cifs    
  #     device: "//u312939.your-storagebox.de/backup/cse"
  #     o: "username=u312939,password=Qr78R4YqxWZyF9Q7,vers=3.0,dir_mode=0777,file_mode=0777"

  # webdav:
  # driver: fentas/davfs
  # driver_opts:
  #   # type: rsync    
  #   # remote: "//u312939.your-storagebox.de/backup/cse"
  #   o: "url=https://u312939:Qr78R4YqxWZyF9Q7@u312939.your-storagebox.de/backup"
